### ISSUE TITLE
Missing string when clicking "Send log report"

### ISSUE THREAD

**Issue by fiazk** [NewEconomyMovement/NEMAndroidApp#200]
The string "comment" was not submitted in the translations table.
![photo_2016-04-04_16-11-12](https://cloud.githubusercontent.com/assets/17099341/14250687/dfe39d56-fa7f-11e5-8983-c18cb7dbf914.jpg)

**Comment by fiazk** [comment]
nem address if bounty applicable: NDAZM2-KCD2XB-4Y7XMM-J5UUZ3-2ZCBHE-MHRHF4-3U3W

**Comment by fiazk** [comment]
Mobile: Samsung S3
Android 4.3
NEM 2.0

**Comment by jabo38** [comment]
Transaction hash: 1caa11550290a8fe6aa83548b7b9d4c6c1355ddf39c8608aa0552e91869a9b5e
Bounty paid.

**Comment by fiazk** [comment]
@fyahfox @jabo38 this still has not been added to the translation table

**Comment by jabo38** [comment]
we need these strings in the table

**Comment by am4n0w4r** [comment]
Fixed in 1.0.50;

**Comment by fiazk** [comment]
I still see this issue with 1.0.52 and the tables do not have this string yet @jabo38 @fyahfox

**Comment by fiazk** [comment]
checked .54 and it's not fixed yet @fyahfox @jabo38

**Comment by fyahfox** [comment]
@fiazk well, people have to translate... Otherwise you will of course see the english string. I guess we are talking about <string name="debug_hint_report_comment">?
