### ISSUE TITLE
Cross platform QR scan does not work

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMAndroidApp#48]
v0.1.24.b1495

QR from iOS doesnt work an Android and the other way round. Sometimes it crashes, sometimes other problems. Please look into it closely since this is very important.

**Comment by am4n0w4r** [comment]
This has been fixed and tested with Android v0.1.25 and iOS v2.0b7, resolved.

**Comment by fyahfox** [comment]
v0.1.25.b1662

There are still issues:
- I cannot import an account from iOs to android
- Scanning an iOs invoice on android first worked, after that the android app always crashed

There might be more, I stopped testing at this point.

Please make sure to check all 12 test cases after you coded a fix:
1-3: from ios to android: my info, invoice, import
4-6: from android to ios: my info, invoice, import
7-9: from ios to ios: my info, invoice, import
10-12: from android to android: my info, invoice, import

**Comment by fyahfox** [comment]
v0.1.28.b2003

I still cannot
- scan an import account QR from both iOs and android
- scan an invoice QR from both iOs and android

**Comment by am4n0w4r** [comment]
Please test this in 0.1.30, fixed weird bug in QR scanner that was due to inconsistent and undocumented Android realizations.

**Comment by fyahfox** [comment]
0.1.30

With this version I was able to scan

- import account QR from both iOS and android
- invoice QR from both iOS and android
- contact (my info) QR from both iOS and android
